version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Dev/hsp-full-site-next
permissions:
  - object: /home/ubuntu/Dev/hsp-full-site-next
    pattern: '*'
hooks:
  BeforeInstall:
    - location: .deploy/scripts/BeforeInstall.sh
      timeout: 300
  AfterInstall:
    - location: .deploy/scripts/AfterInstall.sh
      timeout: 300
