version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Dev/hsp-full-site-next
permissions:
  - object: /home/ubuntu/Dev/hsp-full-site-next
    pattern: '*'
    owner: ubuntu
    mode: 777
