version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Dev/hsp-full-site-next
permissions:
  - owner: ubuntu
hooks:
  AfterInstall:
    - location: deploy/AfterInstall.sh
      timeout: 300
